### ISSUE TITLE
TypeError: 'type' object is not subscriptable - Python 3.8.10

### ISSUE THREAD

**Issue by scriptzteam** [yonatan8070/homelab-fetch#1]
Nice script but i got this error.

```
python3 hlfetch -t root@*.*.*.*
Traceback (most recent call last):
  File "./hlfetch", line 126, in <module>
    def render(machines: List[dict[str, str]]):
TypeError: 'type' object is not subscriptable
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

```
python3 --version
Python 3.8.10
```

**Comment by yonatan8070** [comment]
Could you try changing `dict` to `Dict` on line 126? Apparently the way I was doing it is only an option in Python >= 3.9 (source: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html)

**Comment by scriptzteam** [comment]
Changed
```
python3 hlfetch --help
Traceback (most recent call last):
  File "hlfetch", line 126, in <module>
    def render(machines: List[Dict[str, str]]):
NameError: name 'Dict' is not defined
```

**Comment by scriptzteam** [comment]
Hmm added this one also:

from typing import List, **Dict**

now it run :D

**Comment by scriptzteam** [comment]
Nope, another error spawned.
```
python3 hlfetch -t root@*.*.*.*
root@*.*.*.*'s password:
Traceback (most recent call last):
  File "hlfetch", line 208, in <module>
    main()
  File "hlfetch", line 200, in main
    machine_info = process_ssh_output(ssh_output_str)
  File "hlfetch", line 36, in process_ssh_output
    distro, ansi_color = filter_os_release(command_outputs[0])
  File "hlfetch", line 74, in filter_os_release
    if result["ANSI_COLOR"]:
KeyError: 'ANSI_COLOR'
```

**Comment by scriptzteam** [comment]
Idk why but i commented those lines:
```
    #if result["ANSI_COLOR"]:
        #ansi_color = result["ANSI_COLOR"]
```
and it works now :D

**Comment by yonatan8070** [comment]
These lines are supposed to check whether the distro defines a color to print out. Not all distros specify this, and the check is just written wrong, so it crashes instead of failing gracefully. I'll fix this later to use `try...catch`

I'll also add the `dict` -> `Dict` fix
