### ISSUE TITLE
KeyError: 'ANSI_COLOR' - Python 3.10.4

### ISSUE THREAD

**Issue by scriptzteam** [yonatan8070/homelab-fetch#2]
Another machine, another error.
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
```
```
python3 --version
Python 3.10.4
```
```
python3 hlfetch -t root@*.*.*.*
root@*.*.*.*'s password:
Traceback (most recent call last):
  File "/root/hlfetch", line 208, in <module>
    main()
  File "/root/hlfetch", line 200, in main
    machine_info = process_ssh_output(ssh_output_str)
  File "/root/hlfetch", line 36, in process_ssh_output
    distro, ansi_color = filter_os_release(command_outputs[0])
  File "/root/hlfetch", line 74, in filter_os_release
    if result["ANSI_COLOR"]:
KeyError: 'ANSI_COLOR'
```

**Comment by scriptzteam** [comment]
Idk why but i commented those lines:
```
    #if result["ANSI_COLOR"]:
        #ansi_color = result["ANSI_COLOR"]
```
and it works now :D

**Comment by yonatan8070** [comment]
This is a mistake on my part. 

I'll change this to use a `try...catch` instead of an `if` later, since I'm a little busy right now.

**Comment by yonatan8070** [comment]
Now it also works properly without an `ANSI_COLOR` value.
