### ISSUE TITLE
Doesn't seem to work with shortname/hostname - only with FQDN

### ISSUE THREAD

**Issue by vom513** [yonatan8070/homelab-fetch#3]
```
vom@onosendai 💀 bin % ./hlfetch -t vom@ns2                      
vom@ns2 is not a valid SSH connection string
vom@onosendai 💀 bin % ./hlfetch -t vom@ns2.internal.burn.net    
Traceback (most recent call last):
  File "/Users/vom/bin/./hlfetch", line 208, in <module>
    main()
  File "/Users/vom/bin/./hlfetch", line 200, in main
    machine_info = process_ssh_output(ssh_output_str)
  File "/Users/vom/bin/./hlfetch", line 36, in process_ssh_output
    distro, ansi_color = filter_os_release(command_outputs[0])
  File "/Users/vom/bin/./hlfetch", line 74, in filter_os_release
    if result["ANSI_COLOR"]:
KeyError: 'ANSI_COLOR'
```

**Comment by yonatan8070** [comment]
The first error is probably my regex being broken, I think it should just be removed entirely since I added proper error detection for the SSH process, and it will figure out whether a connection string is valid more reliably than my regex.

The second error is unrelated and is already documented in #2, I will fix it tomorrow when I will get a bit of time

**Comment by yonatan8070** [comment]
Now it will simply fail when the SSH process fails in case of an invalid target
